#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom &

$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
